version: '3'

volumes:
  mysql_data:
  bundle_data:

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/backend:cached
      - bundle_data:/usr/local/bundle
      - /backend/log
      - /backend/.git
    environment:
      TZ: Asia/Tokyo
    ports:
      - '3001:3000'
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: '172.20.0.3'

  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: 'yarn dev'
    networks:
      app_net:
        ipv4_address: '172.20.0.4'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
