require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: false

LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ContextWording:
  Enabled: false


AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
