version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  storage:
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/backend
      - /backend/log
      - /backend/tmp
      - vendor_bundle:/backend/vendor/bundle
      - storage:/backend/storage
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db
